#! /bin/bash
python train.py \
        --data_path /mnt/petrelfs/zhaobin/fpz/NYUv2/ \
        --dataset NYU100 \
        -N gyp5_5 \
        --use_cuda \
        --device 0 \
        -E 400 \
        --BS 8 \
	--eval \
        --visible_image_num 5 \
        --save_checkpoint \
        --save_best \
        --save_last \
        --sm_loss_beta 2.5 \
        --verbose \
        --aif_recon_loss_lambda 100 \
        --aif_blur_loss_lambda 1e1 \
        --blur_loss_lambda 1e1 \
        --sm_loss_lambda 10 \
        --manual_seed 0
